<?php
    include "../assets/files/nav.php";
?>
    <h1>History of Unix</h1>
    <section id="history_1">
        <h2>What is Unix?</h2>
        <p>UNIX is a collection of operating systems that serve as a precursor to several modern operating systems. Several prolific operating systems such as Linux, Mac OS X, Android, Solaris, etc. use its design principles as a basis. </p>
    </section>
    <section id="history_2">
        <h2>Beginnings</h2>
        <p>UNIX started development in 1969 by Ken Thompson and Dennis Ritchie at AT&T Bell Labs. Originally, it was intended to be an interactive time-sharing system, meaning multiple computing tasks could be done concurrently by dividing a computer’s processing power. It was an evolution of an even earlier operating system called Multiplexed Information and Computing Service (or Multics), which itself was meant to let users connect to a computer remotely to perform certain tasks. AT&T provided funding for Multics for five years before deciding it wasn’t going to realistically come to fruition. Disappointed by the company’s decision to halt the development of any new operating systems, Thompson and Ritchie (among others) decided to work on their new project in secret.</p>
        <p>The first version of UNIX was originally made to more optimally run a game Ken Thompson made called Space Travel on a PDP-7 computer, which had a very fast disc drive for the time. This meant that a better operating system could optimize the amount of data that could be transferred through it. It was around this time that the name “UNIX” was created. It comes from what Thompson’s colleagues jokingly referred to as “Un-multiplexed Information and Computing Service." This was “UNICS” for short, which not long after turned into what it eventually became known by. Thompson and Ritchie eventually realized that the PDP-7 was outdated and wouldn’t properly serve their development needs any longer. They were able to convince Bell Labs to give them access to a PDP-11 under the guise of needing it for the development of a program for text formatting. </p>
        <p>The first version was finished in 1971. It was able to be used on the newer PDP-11/20 and its primary function was processing the text of patent documents. It included several features that are standard in operating systems even in the modern day such as a hierarchical file system, which allowed users to arrange files in individual directories that could store other directories. It even included the time-sharing functionality intended to be implemented into Multics. It did not, however, include a graphical user interface. It was something of an early open source program, as users were encouraged to modify and iterate upon the source code.</p>
        <p>In 1973 it was rewritten in C and made portable, meaning it could be used on multiple different platforms. In 1974, a paper about it was released in Communications of the ACM that made interest surge rapidly. AT&T wasn’t legally allowed to sell anything besides telecommunications technologies at this time, so the source code was licensed for a small fee. Because of this, some of the first support groups for UNIX usage appeared. In 1983, UNIX System V was the first commercially available version of UNIX. These two landmarks in its development made it so that UNIX was made widely available.</p>
    </section>
    <section id="history_3">
        <h2>UNIX-based systems today</h2>
        <p>UNIX serves as a basis for how software is used and presented in the modern day, which gives it a large amount of historical significance. Variations of UNIX are used today primarily for servers and workstations but UNIX-based systems are commonly used today for daily computing tasks. The trademark is currently owned by the Open Group, which is a global consortium whose purpose is to set standards for parts of the computing industry. Members highlighted on the Open Group’s site include companies such as IBM, Intel, and even Shell. </p>
        <p>Several commands used in Linux distributions are the exact same commands used in the second edition of UNIX, while some have either changed or no longer exist. Commands such as cat, chdir, mount, mkdir, and more were used for terminal-based file management in the past and still are today. Many of the commands that are still used can be viewed in the tutorial section.</p>
    </section>
</body>
</html>